import "dotenv/config";

import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";

import { hashPassword } from "../src/lib/auth/password";
import { PrismaClient } from "./generated/client/client";
import {
  ActivationCountUnit,
  ActivationMonthCountMode,
  DiscountMethod,
  DiscountTarget,
  InventoryStatus,
  ManualScheduleStatus,
  PaymentMethod,
  PaymentStatus,
  ReceivableStatus,
  RevenueCalculationMethod,
  SaleStatus,
  UserRole,
} from "./generated/client/enums";

const adapter = new PrismaBetterSqlite3(
  { url: process.env.DATABASE_URL || "file:./prisma/dev.db" },
  { timestampFormat: "unixepoch-ms" },
);

const prisma = new PrismaClient({ adapter });

function at(dateTime: string) {
  return new Date(dateTime);
}

async function main() {
  await prisma.$transaction([
    prisma.manualSchedule.deleteMany(),
    prisma.saleAddOnService.deleteMany(),
    prisma.payment.deleteMany(),
    prisma.receivable.deleteMany(),
    prisma.sale.deleteMany(),
    prisma.inventoryItem.deleteMany(),
    prisma.store.deleteMany(),
    prisma.carrierActivationRule.deleteMany(),
    prisma.discountPolicy.deleteMany(),
    prisma.saleProfitPolicy.deleteMany(),
    prisma.staffCommissionPolicy.deleteMany(),
    prisma.rebatePolicy.deleteMany(),
    prisma.addOnService.deleteMany(),
    prisma.ratePlan.deleteMany(),
    prisma.customer.deleteMany(),
    prisma.deviceModel.deleteMany(),
    prisma.carrier.deleteMany(),
    prisma.user.deleteMany(),
  ]);

  await prisma.user.createMany({
    data: [
      {
        id: "user-admin",
        username: "admin",
        displayName: "관리자",
        passwordHash: hashPassword("admin1234!"),
        role: UserRole.ADMIN,
        isActive: true,
      },
      {
        id: "user-kim-jh",
        username: "jihu_kim",
        displayName: "김지후",
        passwordHash: hashPassword("staff1234!"),
        role: UserRole.STAFF,
        isActive: true,
      },
      {
        id: "user-park-sy",
        username: "sunyoung_park",
        displayName: "박선영",
        passwordHash: hashPassword("staff1234!"),
        role: UserRole.STAFF,
        isActive: true,
      },
      {
        id: "user-lee-dy",
        username: "doyoon_lee",
        displayName: "이도윤",
        passwordHash: hashPassword("staff1234!"),
        role: UserRole.STAFF,
        isActive: true,
      },
    ],
  });

  await prisma.store.createMany({
    data: [
      {
        id: "store-main",
        code: "MAIN",
        name: "본점",
        region: "수원",
        isActive: true,
        isDefault: true,
      },
      {
        id: "store-gangnam",
        code: "GNM",
        name: "강남점",
        region: "서울 강남",
        isActive: true,
        isDefault: false,
      },
      {
        id: "store-songpa",
        code: "SGP",
        name: "송파점",
        region: "서울 송파",
        isActive: true,
        isDefault: false,
      },
    ],
  });

  await prisma.carrier.createMany({
    data: [
      { id: "carrier-skt", code: "SKT", name: "SKT", isActive: true },
      { id: "carrier-kt", code: "KT", name: "KT", isActive: true },
      { id: "carrier-lgu", code: "LGU", name: "LG U+", isActive: true },
    ],
  });

  await prisma.carrierActivationRule.createMany({
    data: [
      {
        id: "activation-rule-skt",
        carrierId: "carrier-skt",
        countUnit: ActivationCountUnit.DAY,
        countValue: 93,
        memo: "SKT 기본 의무 유지 기간",
        isActive: true,
      },
      {
        id: "activation-rule-kt",
        carrierId: "carrier-kt",
        countUnit: ActivationCountUnit.DAY,
        countValue: 127,
        memo: "KT 개통 후 127일 기준",
        isActive: true,
      },
      {
        id: "activation-rule-lgu",
        carrierId: "carrier-lgu",
        countUnit: ActivationCountUnit.MONTH,
        countValue: 4,
        monthCountMode: ActivationMonthCountMode.INCLUDE_CURRENT_MONTH,
        memo: "LG U+ 월 단위 기준 예시",
        isActive: true,
      },
    ],
  });

  await prisma.deviceModel.createMany({
    data: [
      {
        id: "device-galaxy-s25",
        name: "Galaxy S25",
        manufacturer: "Samsung",
        isActive: true,
      },
      {
        id: "device-iphone-16",
        name: "iPhone 16",
        manufacturer: "Apple",
        isActive: true,
      },
      {
        id: "device-z-flip-6",
        name: "Galaxy Z Flip 6",
        manufacturer: "Samsung",
        isActive: true,
      },
      {
        id: "device-galaxy-a56",
        name: "Galaxy A56",
        manufacturer: "Samsung",
        isActive: true,
      },
    ],
  });

  await prisma.ratePlan.createMany({
    data: [
      {
        id: "plan-skt-5gx",
        carrierId: "carrier-skt",
        name: "5GX 플래티넘",
        monthlyFee: 109000,
        voiceCallMinutes: 999999,
        videoCallMinutes: 300,
        dataAllowanceGb: 250,
        description: "SKT 프리미엄 5G 요금제",
        isActive: true,
      },
      {
        id: "plan-kt-choice",
        carrierId: "carrier-kt",
        name: "5G 초이스 베이직",
        monthlyFee: 90000,
        voiceCallMinutes: 999999,
        videoCallMinutes: 300,
        dataAllowanceGb: 110,
        description: "KT 대표 5G 요금제",
        isActive: true,
      },
      {
        id: "plan-lgu-premier",
        carrierId: "carrier-lgu",
        name: "5G 프리미어 에센셜",
        monthlyFee: 95000,
        voiceCallMinutes: 999999,
        videoCallMinutes: 300,
        dataAllowanceGb: 150,
        description: "LG U+ 고가형 요금제",
        isActive: true,
      },
    ],
  });

  await prisma.addOnService.createMany({
    data: [
      {
        id: "service-kt-insurance",
        carrierId: "carrier-kt",
        name: "KT 휴대폰 보험",
        monthlyFee: 7900,
        description: "파손/분실 기본 보장",
        isActive: true,
      },
      {
        id: "service-skt-combine",
        carrierId: "carrier-skt",
        name: "가족 결합 할인",
        monthlyFee: 0,
        description: "결합 할인용 선택 항목",
        isActive: true,
      },
      {
        id: "service-lgu-cloud",
        carrierId: "carrier-lgu",
        name: "클라우드 백업",
        monthlyFee: 3300,
        description: "기본 부가서비스 예시",
        isActive: true,
      },
    ],
  });

  await prisma.saleProfitPolicy.createMany({
    data: [
      {
        id: "profit-skt-default-202604",
        name: "SKT",
        carrierId: "carrier-skt",
        startsAt: at("2026-04-01T00:00:00+09:00"),
        endsAt: at("2026-04-30T23:59:59+09:00"),
        calculationMethod: RevenueCalculationMethod.PERCENTAGE,
        calculationValue: 5,
        memo: "판매금액 x 5%",
        isActive: true,
      },
      {
        id: "profit-kt-fixed-202604",
        name: "KT",
        carrierId: "carrier-kt",
        startsAt: at("2026-04-01T00:00:00+09:00"),
        endsAt: at("2026-04-30T23:59:59+09:00"),
        calculationMethod: RevenueCalculationMethod.FIXED_AMOUNT,
        calculationValue: 70000,
        memo: "KT 주력 판매 정액 수익",
        isActive: true,
      },
      {
        id: "profit-lgu-flip-202604",
        name: "LG U+",
        carrierId: "carrier-lgu",
        startsAt: at("2026-04-01T00:00:00+09:00"),
        endsAt: at("2026-04-30T23:59:59+09:00"),
        calculationMethod: RevenueCalculationMethod.FIXED_AMOUNT,
        calculationValue: 120000,
        memo: "Flip 6 집중 판매 기간",
        isActive: true,
      },
    ],
  });

  await prisma.staffCommissionPolicy.createMany({
    data: [
      {
        id: "commission-skt-basic-202604",
        name: "김지후",
        staffId: "user-kim-jh",
        startsAt: at("2026-04-01T00:00:00+09:00"),
        endsAt: at("2026-04-30T23:59:59+09:00"),
        calculationMethod: RevenueCalculationMethod.PERCENTAGE,
        calculationValue: 2,
        memo: "판매가 기준 2% 차감",
        isActive: true,
      },
      {
        id: "commission-kt-basic-202604",
        name: "박선영",
        staffId: "user-park-sy",
        startsAt: at("2026-04-01T00:00:00+09:00"),
        endsAt: at("2026-04-30T23:59:59+09:00"),
        calculationMethod: RevenueCalculationMethod.FIXED_AMOUNT,
        calculationValue: 40000,
        memo: "KT 기본 정액 수수료",
        isActive: true,
      },
      {
        id: "commission-lgu-basic-202604",
        name: "이도윤",
        staffId: "user-lee-dy",
        startsAt: at("2026-04-01T00:00:00+09:00"),
        endsAt: at("2026-04-30T23:59:59+09:00"),
        calculationMethod: RevenueCalculationMethod.FIXED_AMOUNT,
        calculationValue: 50000,
        memo: "LG U+ 기본 정액 수수료",
        isActive: true,
      },
    ],
  });

  await prisma.discountPolicy.createMany({
    data: [
      {
        id: "discount-device-s25-202604",
        name: "Galaxy S25",
        target: DiscountTarget.DEVICE,
        deviceModelId: "device-galaxy-s25",
        startsAt: at("2026-04-11T00:00:00+09:00"),
        endsAt: at("2026-04-20T23:59:59+09:00"),
        discountMethod: DiscountMethod.PERCENTAGE,
        discountValue: 8,
        memo: "단말기 우선 할인",
        isActive: true,
      },
      {
        id: "discount-kt-iphone16-202604",
        name: "iPhone 16",
        target: DiscountTarget.DEVICE,
        deviceModelId: "device-iphone-16",
        startsAt: at("2026-04-01T00:00:00+09:00"),
        endsAt: at("2026-04-30T23:59:59+09:00"),
        discountMethod: DiscountMethod.PERCENTAGE,
        discountValue: 8,
        memo: "KT 주력 단말 할인",
        isActive: true,
      },
    ],
  });

  await prisma.customer.createMany({
    data: [
      {
        id: "customer-kim-seohyun",
        name: "김서현",
        phone: "010-2458-1123",
        normalizedPhone: "01024581123",
        currentCarrierId: "carrier-kt",
      },
      {
        id: "customer-lee-jaemin",
        name: "이재민",
        phone: "010-9034-1120",
        normalizedPhone: "01090341120",
        currentCarrierId: "carrier-skt",
      },
      {
        id: "customer-jung-haeun",
        name: "정하은",
        phone: "010-5612-4430",
        normalizedPhone: "01056124430",
        currentCarrierId: "carrier-lgu",
      },
      {
        id: "customer-oh-sion",
        name: "오시온",
        phone: "010-7784-3312",
        normalizedPhone: "01077843312",
        currentCarrierId: "carrier-skt",
      },
      {
        id: "customer-choi-minwoo",
        name: "최민우",
        phone: "010-9924-7781",
        normalizedPhone: "01099247781",
        currentCarrierId: "carrier-skt",
      },
      {
        id: "customer-yoon-seojin",
        name: "윤서진",
        phone: "010-3112-6708",
        normalizedPhone: "01031126708",
        currentCarrierId: "carrier-kt",
      },
      {
        id: "customer-hwang-nari",
        name: "황나리",
        phone: "010-2874-1194",
        normalizedPhone: "01028741194",
        currentCarrierId: "carrier-lgu",
      },
    ],
  });

  await prisma.inventoryItem.createMany({
    data: [
      {
        id: "inventory-s25-001",
        storeId: "store-main",
        carrierId: "carrier-skt",
        deviceModelId: "device-galaxy-s25",
        color: "Titan Gray",
        capacity: "256GB",
        imei: "357000001245871",
        costAmount: 912000,
        status: InventoryStatus.IN_STOCK,
        receivedAt: at("2026-04-10T10:00:00+09:00"),
        assigneeId: "user-kim-jh",
      },
      {
        id: "inventory-iphone16-001",
        storeId: "store-gangnam",
        carrierId: "carrier-kt",
        deviceModelId: "device-iphone-16",
        color: "Blue",
        capacity: "128GB",
        imei: "356100001245654",
        costAmount: 1045000,
        status: InventoryStatus.SOLD,
        receivedAt: at("2026-04-09T11:00:00+09:00"),
        dispatchedAt: at("2026-04-11T13:20:00+09:00"),
        assigneeId: "user-park-sy",
      },
      {
        id: "inventory-iphone16-002",
        storeId: "store-gangnam",
        carrierId: "carrier-kt",
        deviceModelId: "device-iphone-16",
        color: "Blue",
        capacity: "128GB",
        imei: "356100001245655",
        costAmount: 1045000,
        status: InventoryStatus.RESERVED,
        receivedAt: at("2026-04-10T15:00:00+09:00"),
        assigneeId: "user-park-sy",
      },
      {
        id: "inventory-zflip6-001",
        storeId: "store-songpa",
        carrierId: "carrier-lgu",
        deviceModelId: "device-z-flip-6",
        color: "Mint",
        capacity: "512GB",
        imei: "358200001245338",
        costAmount: 1180000,
        status: InventoryStatus.SOLD,
        receivedAt: at("2026-04-07T14:10:00+09:00"),
        dispatchedAt: at("2026-04-09T16:15:00+09:00"),
        assigneeId: "user-lee-dy",
      },
      {
        id: "inventory-a56-001",
        storeId: "store-main",
        carrierId: "carrier-skt",
        deviceModelId: "device-galaxy-a56",
        color: "Awesome Navy",
        capacity: "256GB",
        imei: "359300001245118",
        costAmount: 620000,
        status: InventoryStatus.SOLD,
        receivedAt: at("2026-04-06T09:30:00+09:00"),
        dispatchedAt: at("2026-04-08T18:40:00+09:00"),
        assigneeId: "user-kim-jh",
      },
      {
        id: "inventory-s25-002",
        storeId: "store-main",
        carrierId: "carrier-skt",
        deviceModelId: "device-galaxy-s25",
        color: "Icy Blue",
        capacity: "512GB",
        imei: "357000001245872",
        costAmount: 918000,
        status: InventoryStatus.SOLD,
        receivedAt: at("2025-11-26T10:10:00+09:00"),
        dispatchedAt: at("2025-12-02T14:40:00+09:00"),
        assigneeId: "user-kim-jh",
      },
      {
        id: "inventory-iphone16-003",
        storeId: "store-gangnam",
        carrierId: "carrier-kt",
        deviceModelId: "device-iphone-16",
        color: "Black",
        capacity: "256GB",
        imei: "356100001245656",
        costAmount: 1089000,
        status: InventoryStatus.SOLD,
        receivedAt: at("2025-11-22T09:45:00+09:00"),
        dispatchedAt: at("2025-11-28T16:30:00+09:00"),
        assigneeId: "user-park-sy",
      },
      {
        id: "inventory-zflip6-002",
        storeId: "store-songpa",
        carrierId: "carrier-lgu",
        deviceModelId: "device-z-flip-6",
        color: "Silver Shadow",
        capacity: "512GB",
        imei: "358200001245339",
        costAmount: 1180000,
        status: InventoryStatus.SOLD,
        receivedAt: at("2025-11-10T12:20:00+09:00"),
        dispatchedAt: at("2025-11-18T17:00:00+09:00"),
        assigneeId: "user-lee-dy",
      },
    ],
  });

  await prisma.sale.createMany({
    data: [
      {
        id: "sale-20260411-kim",
        storeId: "store-gangnam",
        saleDate: at("2026-04-11T13:20:00+09:00"),
        status: SaleStatus.COMPLETED,
        customerId: "customer-kim-seohyun",
        staffId: "user-park-sy",
        carrierId: "carrier-kt",
        ratePlanId: "plan-kt-choice",
        inventoryItemId: "inventory-iphone16-001",
        deviceModelId: "device-iphone-16",
        listPrice: 1400000,
        discountApplied: true,
        discountMethod: DiscountMethod.PERCENTAGE,
        discountValue: 8,
        discountSuggestionMethod: DiscountMethod.PERCENTAGE,
        discountSuggestionValue: 8,
        discountAmount: 112000,
        discountedPrice: 1288000,
        subsidyAmount: 0,
        finalSalePrice: 1288000,
        cashAmount: 200000,
        cardAmount: 788000,
        bankTransferAmount: 0,
        cardInstallmentMonths: 12,
        actualReceivedAmount: 988000,
        receivableAmount: 300000,
        deviceCostAmount: 1045000,
        rebateAmount: 310000,
        policyRevenueAmount: 70000,
        profitCalculationBaseAmount: 1288000,
        profitDeductionAmount: 40000,
        totalProfitAmount: 340000,
        appliedRebatePolicyId: null,
        appliedSaleProfitPolicyId: "profit-kt-fixed-202604",
        appliedStaffCommissionPolicyId: "commission-kt-basic-202604",
        appliedDiscountPolicyId: "discount-kt-iphone16-202604",
        appliedRebatePolicyName: null,
        appliedSaleProfitPolicyName: "KT",
        appliedStaffCommissionPolicyName: "박선영",
        appliedDiscountPolicyName: "iPhone 16",
      },
      {
        id: "sale-20260411-lee",
        storeId: "store-main",
        saleDate: at("2026-04-11T15:10:00+09:00"),
        status: SaleStatus.COMPLETED,
        customerId: "customer-lee-jaemin",
        staffId: "user-kim-jh",
        carrierId: "carrier-skt",
        ratePlanId: "plan-skt-5gx",
        inventoryItemId: "inventory-s25-001",
        deviceModelId: "device-galaxy-s25",
        listPrice: 1200000,
        discountApplied: true,
        discountMethod: DiscountMethod.PERCENTAGE,
        discountValue: 5,
        discountSuggestionMethod: DiscountMethod.PERCENTAGE,
        discountSuggestionValue: 8,
        discountAmount: 60000,
        discountedPrice: 1140000,
        subsidyAmount: 0,
        finalSalePrice: 1140000,
        cashAmount: 340000,
        cardAmount: 800000,
        bankTransferAmount: 0,
        cardInstallmentMonths: 6,
        actualReceivedAmount: 1140000,
        receivableAmount: 0,
        deviceCostAmount: 912000,
        rebateAmount: 250000,
        policyRevenueAmount: 0,
        profitCalculationBaseAmount: 1140000,
        profitDeductionAmount: 22800,
        totalProfitAmount: 227200,
        appliedSaleProfitPolicyId: "profit-skt-default-202604",
        appliedStaffCommissionPolicyId: "commission-skt-basic-202604",
        appliedDiscountPolicyId: "discount-device-s25-202604",
        appliedSaleProfitPolicyName: "SKT",
        appliedStaffCommissionPolicyName: "김지후",
        appliedDiscountPolicyName: "Galaxy S25",
      },
      {
        id: "sale-20260409-jung",
        storeId: "store-songpa",
        saleDate: at("2026-04-09T16:15:00+09:00"),
        status: SaleStatus.COMPLETED,
        customerId: "customer-jung-haeun",
        staffId: "user-lee-dy",
        carrierId: "carrier-lgu",
        ratePlanId: "plan-lgu-premier",
        inventoryItemId: "inventory-zflip6-001",
        deviceModelId: "device-z-flip-6",
        listPrice: 1390000,
        discountApplied: false,
        discountAmount: 0,
        discountedPrice: 1390000,
        subsidyAmount: 0,
        finalSalePrice: 1390000,
        cashAmount: 0,
        cardAmount: 970000,
        bankTransferAmount: 0,
        cardInstallmentMonths: 12,
        actualReceivedAmount: 970000,
        receivableAmount: 420000,
        deviceCostAmount: 1180000,
        rebateAmount: 420000,
        policyRevenueAmount: 120000,
        profitCalculationBaseAmount: 1390000,
        profitDeductionAmount: 50000,
        totalProfitAmount: 490000,
        appliedRebatePolicyId: null,
        appliedSaleProfitPolicyId: "profit-lgu-flip-202604",
        appliedStaffCommissionPolicyId: "commission-lgu-basic-202604",
        appliedRebatePolicyName: null,
        appliedSaleProfitPolicyName: "LG U+",
        appliedStaffCommissionPolicyName: "이도윤",
      },
      {
        id: "sale-20260408-oh",
        storeId: "store-main",
        saleDate: at("2026-04-08T18:40:00+09:00"),
        status: SaleStatus.COMPLETED,
        customerId: "customer-oh-sion",
        staffId: "user-kim-jh",
        carrierId: "carrier-skt",
        ratePlanId: "plan-skt-5gx",
        inventoryItemId: "inventory-a56-001",
        deviceModelId: "device-galaxy-a56",
        listPrice: 880000,
        discountApplied: true,
        discountMethod: DiscountMethod.FIXED_AMOUNT,
        discountValue: 80000,
        discountSuggestionMethod: DiscountMethod.PERCENTAGE,
        discountSuggestionValue: 5,
        discountAmount: 80000,
        discountedPrice: 800000,
        subsidyAmount: 0,
        finalSalePrice: 800000,
        cashAmount: 200000,
        cardAmount: 220000,
        bankTransferAmount: 0,
        cardInstallmentMonths: 3,
        actualReceivedAmount: 420000,
        receivableAmount: 380000,
        deviceCostAmount: 620000,
        rebateAmount: 0,
        policyRevenueAmount: 0,
        profitCalculationBaseAmount: 800000,
        profitDeductionAmount: 16000,
        totalProfitAmount: 0,
        appliedSaleProfitPolicyId: "profit-skt-default-202604",
        appliedStaffCommissionPolicyId: "commission-skt-basic-202604",
        appliedSaleProfitPolicyName: "SKT",
        appliedStaffCommissionPolicyName: "김지후",
      },
      {
        id: "sale-20251202-choi",
        storeId: "store-main",
        saleDate: at("2025-12-02T14:40:00+09:00"),
        status: SaleStatus.COMPLETED,
        customerId: "customer-choi-minwoo",
        staffId: "user-kim-jh",
        carrierId: "carrier-skt",
        ratePlanId: "plan-skt-5gx",
        inventoryItemId: "inventory-s25-002",
        deviceModelId: "device-galaxy-s25",
        listPrice: 1230000,
        discountApplied: false,
        discountAmount: 0,
        discountedPrice: 1230000,
        subsidyAmount: 0,
        finalSalePrice: 1230000,
        cashAmount: 430000,
        cardAmount: 800000,
        bankTransferAmount: 0,
        cardInstallmentMonths: 10,
        actualReceivedAmount: 1230000,
        receivableAmount: 0,
        deviceCostAmount: 918000,
        rebateAmount: 0,
        policyRevenueAmount: 61500,
        profitCalculationBaseAmount: 1230000,
        profitDeductionAmount: 0,
        totalProfitAmount: 312000,
        appliedSaleProfitPolicyName: "이전 판매 기준 데이터",
      },
      {
        id: "sale-20251128-yoon",
        storeId: "store-gangnam",
        saleDate: at("2025-11-28T16:30:00+09:00"),
        status: SaleStatus.COMPLETED,
        customerId: "customer-yoon-seojin",
        staffId: "user-park-sy",
        carrierId: "carrier-kt",
        ratePlanId: "plan-kt-choice",
        inventoryItemId: "inventory-iphone16-003",
        deviceModelId: "device-iphone-16",
        listPrice: 1430000,
        discountApplied: false,
        discountAmount: 0,
        discountedPrice: 1430000,
        subsidyAmount: 0,
        finalSalePrice: 1430000,
        cashAmount: 580000,
        cardAmount: 850000,
        bankTransferAmount: 0,
        cardInstallmentMonths: 12,
        actualReceivedAmount: 1430000,
        receivableAmount: 0,
        deviceCostAmount: 1089000,
        rebateAmount: 0,
        policyRevenueAmount: 70000,
        profitCalculationBaseAmount: 1430000,
        profitDeductionAmount: 0,
        totalProfitAmount: 411000,
        appliedSaleProfitPolicyName: "이전 판매 기준 데이터",
      },
      {
        id: "sale-20251118-hwang",
        storeId: "store-songpa",
        saleDate: at("2025-11-18T17:00:00+09:00"),
        status: SaleStatus.COMPLETED,
        customerId: "customer-hwang-nari",
        staffId: "user-lee-dy",
        carrierId: "carrier-lgu",
        ratePlanId: "plan-lgu-premier",
        inventoryItemId: "inventory-zflip6-002",
        deviceModelId: "device-z-flip-6",
        listPrice: 1370000,
        discountApplied: false,
        discountAmount: 0,
        discountedPrice: 1370000,
        subsidyAmount: 0,
        finalSalePrice: 1370000,
        cashAmount: 370000,
        cardAmount: 1000000,
        bankTransferAmount: 0,
        cardInstallmentMonths: 12,
        actualReceivedAmount: 1370000,
        receivableAmount: 0,
        deviceCostAmount: 1180000,
        rebateAmount: 0,
        policyRevenueAmount: 0,
        profitCalculationBaseAmount: 1370000,
        profitDeductionAmount: 0,
        totalProfitAmount: 190000,
        appliedSaleProfitPolicyName: "이전 판매 기준 데이터",
      },
    ],
  });

  await prisma.saleAddOnService.createMany({
    data: [
      {
        saleId: "sale-20260411-kim",
        addOnServiceId: "service-kt-insurance",
        nameSnapshot: "KT 휴대폰 보험",
        monthlyFee: 7900,
      },
      {
        saleId: "sale-20260408-oh",
        addOnServiceId: "service-skt-combine",
        nameSnapshot: "가족 결합 할인",
        monthlyFee: 0,
      },
    ],
  });

  await prisma.receivable.createMany({
    data: [
      {
        id: "receivable-sale-kim",
        saleId: "sale-20260411-kim",
        customerId: "customer-kim-seohyun",
        status: ReceivableStatus.PARTIALLY_PAID,
        originalAmount: 300000,
        balanceAmount: 180000,
        memo: "오늘 방문 예정",
      },
      {
        id: "receivable-sale-jung",
        saleId: "sale-20260409-jung",
        customerId: "customer-jung-haeun",
        status: ReceivableStatus.UNPAID,
        originalAmount: 420000,
        balanceAmount: 420000,
        memo: "3일 경과",
      },
      {
        id: "receivable-sale-oh",
        saleId: "sale-20260408-oh",
        customerId: "customer-oh-sion",
        status: ReceivableStatus.UNPAID,
        originalAmount: 380000,
        balanceAmount: 380000,
        memo: "오늘 수납 약속",
      },
    ],
  });

  await prisma.payment.createMany({
    data: [
      {
        id: "payment-kim-1",
        storeId: "store-gangnam",
        receivableId: "receivable-sale-kim",
        saleId: "sale-20260411-kim",
        staffId: "user-park-sy",
        paymentDate: at("2026-04-11T18:00:00+09:00"),
        amount: 120000,
        method: PaymentMethod.BANK_TRANSFER,
        memo: "1차 부분 수납",
      },
      {
        id: "payment-kim-canceled",
        storeId: "store-gangnam",
        receivableId: "receivable-sale-kim",
        saleId: "sale-20260411-kim",
        staffId: "user-park-sy",
        canceledById: "user-admin",
        paymentDate: at("2026-04-12T11:30:00+09:00"),
        amount: 30000,
        method: PaymentMethod.CASH,
        status: PaymentStatus.CANCELED,
        memo: "중복으로 잘못 등록된 현금 수납",
        canceledAt: at("2026-04-12T11:40:00+09:00"),
        cancellationReason: "중복 입력 정정",
      },
    ],
  });

  await prisma.manualSchedule.createMany({
    data: [
      {
        id: "manual-schedule-kim-followup",
        title: "김서현 잔금 재안내",
        scheduledDate: at("2026-04-21T14:00:00+09:00"),
        status: ManualScheduleStatus.OPEN,
        customerId: "customer-kim-seohyun",
        saleId: "sale-20260411-kim",
        memo: "부분 수납 후 잔액 18만원 재안내 및 방문 일정 확인",
        createdById: "user-park-sy",
      },
      {
        id: "manual-schedule-oh-visit",
        title: "오시온 방문 약속 확인",
        scheduledDate: at("2026-04-22T16:30:00+09:00"),
        status: ManualScheduleStatus.OPEN,
        customerId: "customer-oh-sion",
        saleId: "sale-20260408-oh",
        memo: "미수금 수납 가능 시간 재확인",
        createdById: "user-kim-jh",
      },
      {
        id: "manual-schedule-team-brief",
        title: "주간 매장 브리핑",
        scheduledDate: at("2026-04-25T09:30:00+09:00"),
        status: ManualScheduleStatus.DONE,
        memo: "강남점/본점 4월 마지막 주 판매 현황 공유",
        createdById: "user-admin",
      },
      {
        id: "manual-schedule-jung-canceled",
        title: "정하은 보상정책 재안내",
        scheduledDate: at("2026-04-29T11:00:00+09:00"),
        status: ManualScheduleStatus.CANCELED,
        customerId: "customer-jung-haeun",
        saleId: "sale-20260409-jung",
        memo: "고객 요청으로 다음 달 초로 연기",
        createdById: "user-lee-dy",
      },
    ],
  });
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (error) => {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  });


